Repository servactory/servactory, pull requests merged in 2023-06, with the labels that each got.

#41 Improve English documentation
  docs/pages/getting-started.md
  docs/pages/home.md
  docs/pages/i18n.md
  docs/pages/usage/call.md
  docs/pages/usage/failures.md
  docs/pages/usage/input.md
  docs/pages/usage/internal.md
  docs/pages/usage/make.md
  docs/pages/usage/output.md
  docs/pages/usage/result.md
Labels: documentation

#55 Improve examples and texts in documentation
  docs/i18n/ru/docusaurus-plugin-content-docs/current/testing.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/call.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/configuration.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/failures.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/i18n.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/input.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/internal.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/make.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/output.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/result.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/testing.md
  docs/pages/i18n.md
  docs/pages/usage/call.md
  docs/pages/usage/failures.md
  docs/pages/usage/i18n.md
  docs/pages/usage/input.md
  docs/pages/usage/internal.md
  docs/pages/usage/make.md
  docs/pages/usage/testing.md
  examples/usual/example36.rb
  spec/examples/usual/example36_spec.rb
Labels: documentation

#56 Move documentation site from `docs` to `website`
  website/.gitignore
  website/README.md
  website/babel.config.js
  website/docs/CHANGELOG.md
  website/docs/CODE_OF_CONDUCT.md
  website/docs/CONTRIBUTING.md
  website/docs/getting-started.md
  website/docs/home.md
  website/docs/usage/_category_.yml
  website/docs/usage/call.md
  website/docs/usage/configuration.md
  website/docs/usage/failures.md
  website/docs/usage/i18n.md
  website/docs/usage/input.md
  website/docs/usage/internal.md
  website/docs/usage/make.md
  website/docs/usage/output.md
  website/docs/usage/result.md
  website/docs/usage/testing.md
  website/docusaurus.config.js
  website/i18n/ru/docusaurus-plugin-content-docs/current/CHANGELOG.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/CODE_OF_CONDUCT.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/CONTRIBUTING.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/getting-started.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/home.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/_category_.yml
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/call.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/failures.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/i18n.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/input.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/internal.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/make.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/output.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/result.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/testing.md
  website/package.json
  website/sidebars.js
  website/src/css/custom.css
  website/src/pages/markdown-page.md
  website/static/.nojekyll
  website/static/img/favicon.ico
  website/static/robots.txt
  website/tsconfig.json
  website/yarn.lock
Labels: documentation

#57 Update libraries from 03.06.2023
  Gemfile.lock
  examples/usual/example34.rb
  website/yarn.lock
Labels: dependencies

#59 Use stage collections
  lib/servactory/methods/dsl.rb
  lib/servactory/methods/method_collection.rb
  lib/servactory/methods/stage.rb
  lib/servactory/methods/stage_collection.rb
  lib/servactory/methods/workbench.rb
  sig/lib/servactory/methods/collection.rbs
  sig/lib/servactory/methods/dsl.rbs
  sig/lib/servactory/methods/method_collection.rbs
  sig/lib/servactory/methods/stage.rbs
  sig/lib/servactory/methods/stage_collection.rbs
  sig/lib/servactory/methods/workbench.rbs
Labels: feature

#58 Add `stage` with `wrap_in` and `rollback` support
  examples/usual/example37.rb
  examples/usual/example38.rb
  examples/usual/example39.rb
  examples/usual/example40.rb
  examples/usual/example41.rb
  examples/usual/example42.rb
  lib/servactory/methods/dsl.rb
  lib/servactory/methods/method_collection.rb
  lib/servactory/methods/stage.rb
  lib/servactory/methods/stage_collection.rb
  lib/servactory/methods/workbench.rb
  sig/lib/servactory/methods/collection.rbs
  sig/lib/servactory/methods/dsl.rbs
  sig/lib/servactory/methods/method_collection.rbs
  sig/lib/servactory/methods/stage.rbs
  sig/lib/servactory/methods/stage_collection.rbs
  sig/lib/servactory/methods/workbench.rbs
  spec/examples/usual/example37_spec.rb
  spec/examples/usual/example38_spec.rb
  spec/examples/usual/example39_spec.rb
  spec/examples/usual/example40_spec.rb
  spec/examples/usual/example41_spec.rb
  spec/examples/usual/example42_spec.rb
  website/docs/usage/methods.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/methods.md
Labels: feature

#60 Improve examples in documentation and repository
  README.md
  examples/usual/example43.rb
  lib/servactory/outputs/validations/type.rb
  sig/lib/servactory/outputs/checks/type.rbs
  spec/examples/usual/example43_spec.rb
Labels: documentation

#61 Add helpers for `input`
  examples/usual/example44.rb
  examples/usual/example45.rb
  examples/wrong/example16.rb
  examples/wrong/example17.rb
  lib/servactory/inputs/dsl.rb
  lib/servactory/inputs/input.rb
  lib/servactory/internals/validations/type.rb
  sig/lib/servactory/inputs/dsl.rbs
  sig/lib/servactory/inputs/input.rbs
  sig/lib/servactory/internals/checks/type.rbs
  spec/examples/usual/example44_spec.rb
  spec/examples/usual/example45_spec.rb
  spec/examples/wrong/example16_spec.rb
  spec/examples/wrong/example17_spec.rb
  website/docs/usage/input.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/input.md
Labels: feature

#62 Improve work and prepare tools for testing
  lib/servactory/context/callable.rb
  lib/servactory/context/workspace.rb
  lib/servactory/inputs/validations/type.rb
  lib/servactory/test/fake_type.rb
  lib/servactory/test/result.rb
  sig/lib/servactory/context/workspace.rbs
  sig/lib/servactory/test/fake_type.rbs
  sig/lib/servactory/test/result.rbs
  spec/support/shared_examples/input_type_check.rb
Labels: fix

#63 Add custom helpers for `input`
  examples/application_service/base.rb
  examples/usual/example46.rb
  lib/servactory/configuration/factory.rb
  lib/servactory/configuration/setup.rb
  lib/servactory/inputs/input.rb
  lib/servactory/inputs/option_helper.rb
  lib/servactory/inputs/option_helpers_collection.rb
  sig/lib/servactory/configuration/factory.rbs
  sig/lib/servactory/configuration/setup.rbs
  sig/lib/servactory/inputs/input.rbs
  sig/lib/servactory/inputs/option_helper.rbs
  sig/lib/servactory/inputs/option_helpers_collection.rbs
  spec/examples/usual/example46_spec.rb
  website/docs/usage/configuration.md
  website/docs/usage/input.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/input.md
Labels: feature

#64 Add and update texts in documentation
  website/docs/getting-started.md
  website/docs/home.md
  website/docs/usage/call.md
  website/docs/usage/configuration.md
  website/docs/usage/failures.md
  website/docs/usage/i18n.md
  website/docs/usage/input.md
  website/docs/usage/internal.md
  website/docs/usage/methods.md
  website/docs/usage/output.md
  website/docs/usage/result.md
  website/docs/usage/testing.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/getting-started.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/call.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/failures.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/i18n.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/input.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/internal.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/methods.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/output.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/result.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/testing.md
Labels: documentation

#65 Add `prepare` option to `input`
  examples/usual/example47.rb
  examples/wrong/example18.rb
  examples/wrong/example19.rb
  examples/wrong/example20.rb
  examples/wrong/example21.rb
  examples/wrong/example6.rb
  lib/servactory/inputs/input.rb
  lib/servactory/inputs/tools/prepare.rb
  sig/lib/servactory/inputs/input.rbs
  spec/examples/usual/example47_spec.rb
  spec/examples/wrong/example18_spec.rb
  spec/examples/wrong/example19_spec.rb
  spec/examples/wrong/example20_spec.rb
  spec/examples/wrong/example21_spec.rb
  website/docs/usage/configuration.md
  website/docs/usage/input.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/input.md
Labels: feature

#66 Update examples
  examples/application_service/base.rb
  examples/usual/example28.rb
  examples/usual/example46.rb
Labels: polish

#67 Update libraries from 12.06.2023
  Gemfile.lock
  website/yarn.lock
Labels: dependencies

#68 Add `only_if` method for `stage`
  examples/usual/example48.rb
  examples/usual/example49.rb
  lib/servactory/methods/dsl.rb
  lib/servactory/methods/stage.rb
  lib/servactory/methods/workbench.rb
  sig/lib/servactory/methods/dsl.rbs
  sig/lib/servactory/methods/stage.rbs
  sig/lib/servactory/methods/workbench.rbs
  spec/examples/usual/example48_spec.rb
  spec/examples/usual/example49_spec.rb
  website/docs/usage/methods.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/methods.md
Labels: feature

#69 Fix conflict between input and output
  examples/usual/example50.rb
  lib/servactory/inputs/tools/prepare.rb
  lib/servactory/internals/tools/prepare.rb
  lib/servactory/outputs/tools/prepare.rb
  sig/lib/servactory/outputs/tools/conflicts.rbs
  spec/examples/usual/example50_spec.rb
Labels: fix

#70 Fix variable definition
  examples/usual/example50.rb
  lib/servactory/outputs/tools/prepare.rb
Labels: fix

#71 Improve functionality
  lib/servactory/context/workspace.rb
  lib/servactory/inputs/validations/required.rb
  lib/servactory/utils.rb
  sig/lib/servactory/context/workspace.rbs
  sig/lib/servactory/utils.rbs
Labels: fix

#73 Rename `Test` to `TestKit`
  lib/servactory/test_kit/fake_type.rb
  lib/servactory/test_kit/result.rb
  sig/lib/servactory/test/fake_type.rbs
  sig/lib/servactory/test/result.rbs
  spec/support/shared_examples/input_type_check.rb
Labels: feature

#72 Add ability to get information about class
  lib/servactory/base.rb
  lib/servactory/info/dsl.rb
  lib/servactory/info/result.rb
  sig/lib/servactory/info/dsl.rbs
  sig/lib/servactory/info/result.rbs
  spec/examples/usual/example10_spec.rb
  spec/examples/usual/example11_spec.rb
  spec/examples/usual/example12_spec.rb
  spec/examples/usual/example13_spec.rb
  spec/examples/usual/example14_spec.rb
  spec/examples/usual/example15_spec.rb
  spec/examples/usual/example16_spec.rb
  spec/examples/usual/example17_spec.rb
  spec/examples/usual/example18_spec.rb
  spec/examples/usual/example19_spec.rb
  spec/examples/usual/example1_spec.rb
  spec/examples/usual/example20_spec.rb
  spec/examples/usual/example21_spec.rb
  spec/examples/usual/example22_spec.rb
  spec/examples/usual/example23_spec.rb
  spec/examples/usual/example24_spec.rb
  spec/examples/usual/example25_spec.rb
  spec/examples/usual/example26_spec.rb
  spec/examples/usual/example27_spec.rb
  spec/examples/usual/example28_spec.rb
  spec/examples/usual/example29_spec.rb
  spec/examples/usual/example2_spec.rb
  spec/examples/usual/example30_spec.rb
  spec/examples/usual/example31_spec.rb
  spec/examples/usual/example32_spec.rb
  spec/examples/usual/example33_spec.rb
  spec/examples/usual/example34_spec.rb
  spec/examples/usual/example35_spec.rb
  spec/examples/usual/example36_spec.rb
  spec/examples/usual/example37_spec.rb
  spec/examples/usual/example38_spec.rb
  spec/examples/usual/example39_spec.rb
  spec/examples/usual/example3_spec.rb
  spec/examples/usual/example40_spec.rb
  spec/examples/usual/example41_spec.rb
  spec/examples/usual/example42_spec.rb
  spec/examples/usual/example43_spec.rb
  spec/examples/usual/example44_spec.rb
  spec/examples/usual/example45_spec.rb
  spec/examples/usual/example46_spec.rb
  spec/examples/usual/example47_spec.rb
  spec/examples/usual/example48_spec.rb
  spec/examples/usual/example49_spec.rb
  spec/examples/usual/example4_spec.rb
  spec/examples/usual/example50_spec.rb
  spec/examples/usual/example5_spec.rb
  spec/examples/usual/example6_spec.rb
  spec/examples/usual/example7_spec.rb
  spec/examples/usual/example8_spec.rb
  spec/examples/usual/example9_spec.rb
  spec/support/shared_examples/check_class_info.rb
  website/docs/usage/call.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/call.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/testing.md
Labels: feature

#75 Add analytics to documentation
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: documentation

#78 Create documentation version 1.6
  website/docusaurus.config.js
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/CHANGELOG.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/CODE_OF_CONDUCT.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/CONTRIBUTING.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/getting-started.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/home.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/_category_.yml
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/attributes/_category_.yml
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/attributes/input.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/attributes/internal.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/attributes/output.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/call.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/failures.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/i18n.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/methods.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.6/usage/testing.md
  website/versioned_docs/version-1.6/CHANGELOG.md
  website/versioned_docs/version-1.6/CODE_OF_CONDUCT.md
  website/versioned_docs/version-1.6/CONTRIBUTING.md
  website/versioned_docs/version-1.6/getting-started.md
  website/versioned_docs/version-1.6/home.md
  website/versioned_docs/version-1.6/usage/_category_.yml
  website/versioned_docs/version-1.6/usage/attributes/_category_.yml
  website/versioned_docs/version-1.6/usage/attributes/input.md
  website/versioned_docs/version-1.6/usage/attributes/internal.md
  website/versioned_docs/version-1.6/usage/attributes/output.md
  website/versioned_docs/version-1.6/usage/call.md
  website/versioned_docs/version-1.6/usage/configuration.md
  website/versioned_docs/version-1.6/usage/failures.md
  website/versioned_docs/version-1.6/usage/i18n.md
  website/versioned_docs/version-1.6/usage/methods.md
  website/versioned_docs/version-1.6/usage/testing.md
  website/versioned_sidebars/version-1.6-sidebars.json
  website/versions.json
Labels: documentation

#77 Update documentation for new attributes
  README.md
  website/docs/usage/attributes/input.md
  website/docs/usage/attributes/internal.md
  website/docs/usage/attributes/output.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/attributes/input.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/attributes/internal.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/attributes/output.md
Labels: documentation

#79 Add `error` method and update examples
  .github/workflows/update-changelog.yaml
  README.md
  lib/servactory/context/workspace.rb
  lib/servactory/result.rb
  sig/lib/servactory/context/workspace.rbs
  spec/examples/usual/example20_spec.rb
  spec/examples/usual/example25_spec.rb
  spec/examples/usual/example43_spec.rb
  spec/examples/usual/example50_spec.rb
  website/docs/home.md
  website/docs/usage/call_and_result.md
  website/docusaurus.config.js
  website/i18n/ru/docusaurus-plugin-content-docs/current/home.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/call_and_result.md
  website/src/theme/Layout/index.tsx
Labels: feature

#80 Add generator for CHANGELOG.md
  Gemfile.lock
  bin/changelog
  website/docs/CHANGELOG.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/CHANGELOG.md
Labels: documentation

#81 Improve result of service
  lib/servactory/context/callable.rb
  lib/servactory/context/workspace.rb
  lib/servactory/errors/collection.rb
  lib/servactory/result.rb
  sig/lib/servactory/context/workspace.rbs
  sig/lib/servactory/result.rbs
  spec/examples/usual/example20_spec.rb
  spec/examples/usual/example25_spec.rb
  spec/examples/usual/example42_spec.rb
  spec/examples/usual/example43_spec.rb
  spec/examples/usual/example50_spec.rb
  website/docs/usage/call_and_result.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/call_and_result.md
Labels: fix

#82 Add alias support for `make`
  examples/usual/example45.rb
  lib/servactory/configuration/factory.rb
  lib/servactory/configuration/setup.rb
  lib/servactory/methods/dsl.rb
  lib/servactory/methods/make_aliases/collection.rb
  sig/lib/servactory/configuration/factory.rbs
  sig/lib/servactory/configuration/setup.rbs
  sig/lib/servactory/methods/dsl.rbs
  sig/lib/servactory/methods/make_aliases/collection.rbs
  spec/examples/usual/example45_spec.rb
  website/docs/usage/call_and_result.md
  website/docs/usage/methods.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/methods.md
Labels: feature

#85 Create documentation version 1.7
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/CHANGELOG.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/CODE_OF_CONDUCT.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/CONTRIBUTING.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/getting-started.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/home.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/_category_.yml
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/attributes/_category_.yml
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/attributes/input.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/attributes/internal.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/attributes/output.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/call_and_result.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/failures.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/i18n.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/methods.md
  website/i18n/ru/docusaurus-plugin-content-docs/version-1.7/usage/testing.md
  website/versioned_docs/version-1.7/CHANGELOG.md
  website/versioned_docs/version-1.7/CODE_OF_CONDUCT.md
  website/versioned_docs/version-1.7/CONTRIBUTING.md
  website/versioned_docs/version-1.7/getting-started.md
  website/versioned_docs/version-1.7/home.md
  website/versioned_docs/version-1.7/usage/_category_.yml
  website/versioned_docs/version-1.7/usage/attributes/_category_.yml
  website/versioned_docs/version-1.7/usage/attributes/input.md
  website/versioned_docs/version-1.7/usage/attributes/internal.md
  website/versioned_docs/version-1.7/usage/attributes/output.md
  website/versioned_docs/version-1.7/usage/call_and_result.md
  website/versioned_docs/version-1.7/usage/configuration.md
  website/versioned_docs/version-1.7/usage/failures.md
  website/versioned_docs/version-1.7/usage/i18n.md
  website/versioned_docs/version-1.7/usage/methods.md
  website/versioned_docs/version-1.7/usage/testing.md
  website/versioned_sidebars/version-1.7-sidebars.json
  website/versions.json
Labels: documentation

#83 Rename `method_shortcuts` to `shortcuts_for_make`
  examples/usual/example28.rb
  lib/servactory/configuration/factory.rb
  lib/servactory/configuration/setup.rb
  lib/servactory/methods/aliases_for_make/collection.rb
  lib/servactory/methods/dsl.rb
  lib/servactory/methods/shortcuts_for_make/collection.rb
  sig/lib/servactory/configuration/factory.rbs
  sig/lib/servactory/configuration/setup.rbs
  sig/lib/servactory/methods/aliases_for_make/collection.rbs
  sig/lib/servactory/methods/dsl.rbs
  sig/lib/servactory/methods/shortcuts_for_make/collection.rbs
  website/docs/usage/configuration.md
  website/docs/usage/methods.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/configuration.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/methods.md
Labels: breaking-change

#86 Improve display of attributes in IDE
  lib/servactory/inputs/dsl.rb
  lib/servactory/inputs/input.rb
  lib/servactory/internals/dsl.rb
  lib/servactory/internals/internal.rb
  lib/servactory/outputs/dsl.rb
  lib/servactory/outputs/output.rb
  sig/lib/servactory/inputs/dsl.rbs
  sig/lib/servactory/inputs/input.rbs
  sig/lib/servactory/internals/dsl.rbs
  sig/lib/servactory/internals/internal.rbs
  sig/lib/servactory/outputs/dsl.rbs
  sig/lib/servactory/outputs/output.rbs
Labels: polish

#87 Improve result
  examples/usual/example51.rb
  examples/wrong/example22.rb
  lib/servactory/result.rb
  sig/lib/servactory/result.rbs
  spec/examples/usual/example51_spec.rb
  spec/examples/wrong/example22_spec.rb
  website/docs/usage/call_and_result.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/usage/call_and_result.md
Labels: feature

#88 Improve input options
  lib/servactory/inputs/input.rb
  lib/servactory/inputs/options_collection.rb
  sig/lib/servactory/context/callable.rbs
  sig/lib/servactory/context/workspace/inputs.rbs
  sig/lib/servactory/context/workspace/internals.rbs
  sig/lib/servactory/context/workspace/outputs.rbs
  sig/lib/servactory/inputs/collection.rbs
  sig/lib/servactory/inputs/input.rbs
  sig/lib/servactory/inputs/options_collection.rbs
  sig/lib/servactory/internals/collection.rbs
  sig/lib/servactory/outputs/collection.rbs
Labels: feature

#89 Steep and RBS
  Gemfile.lock
  Steepfile
  lib/servactory/context/workspace/internals.rb
  lib/servactory/context/workspace/outputs.rb
  lib/servactory/methods/dsl.rb
  rbs_collection.lock.yaml
  servactory.gemspec
  sig/lib/servactory/inputs/option.rbs
  sig/lib/servactory/inputs/tools/validation.rbs
  sig/lib/servactory/methods/dsl.rbs
  sig/lib/servactory/methods/method_collection.rbs
  sig/lib/servactory/methods/stage.rbs
  sig/lib/servactory/result.rbs
  sig/lib/servactory/utils.rbs
Labels: tests

#91 Add check for presence of attributes
  lib/servactory/context/workspace/internals.rb
  lib/servactory/context/workspace/outputs.rb
Labels: fix

#92 Improve data processing and performance
  examples/usual/example16.rb
  examples/usual/example17.rb
  lib/servactory/context/callable.rb
  lib/servactory/context/dsl.rb
  lib/servactory/context/store.rb
  lib/servactory/context/workspace.rb
  lib/servactory/context/workspace/inputs.rb
  lib/servactory/context/workspace/internals.rb
  lib/servactory/context/workspace/outputs.rb
  lib/servactory/inputs/dsl.rb
  lib/servactory/inputs/workbench.rb
  lib/servactory/inputs/workspace.rb
  lib/servactory/internals/dsl.rb
  lib/servactory/internals/workbench.rb
  lib/servactory/methods/dsl.rb
  lib/servactory/methods/tools/runner.rb
  lib/servactory/methods/workbench.rb
  lib/servactory/methods/workspace.rb
  lib/servactory/outputs/dsl.rb
  lib/servactory/outputs/workbench.rb
  lib/servactory/outputs/workspace.rb
  lib/servactory/result.rb
  sig/lib/servactory/context/callable.rbs
  sig/lib/servactory/context/store.rbs
  sig/lib/servactory/context/workspace.rbs
  sig/lib/servactory/context/workspace/inputs.rbs
  sig/lib/servactory/context/workspace/internals.rbs
  sig/lib/servactory/context/workspace/outputs.rbs
  sig/lib/servactory/inputs/dsl.rbs
  sig/lib/servactory/inputs/workbench.rbs
  sig/lib/servactory/inputs/workspace.rbs
  sig/lib/servactory/internals/dsl.rbs
  sig/lib/servactory/internals/workbench.rbs
  sig/lib/servactory/methods/tools/runner.rbs
  sig/lib/servactory/methods/workbench.rbs
  sig/lib/servactory/methods/workspace.rbs
  sig/lib/servactory/outputs/dsl.rbs
  sig/lib/servactory/outputs/workbench.rbs
  sig/lib/servactory/outputs/workspace.rbs
  sig/lib/servactory/result.rbs
  spec/examples/usual/example23_spec.rb
  spec/examples/usual/example50_spec.rb
  spec/examples/wrong/example22_spec.rb
Labels: fix

#93 Harmlessly getting data from internals and outputs
  examples/wrong/example23.rb
  lib/servactory/context/workspace.rb
  spec/examples/wrong/example23_spec.rb
Labels: fix
