Repository servactory/servactory, pull requests merged in 2023-05, with the labels that each got.

#3 Add support for Ruby 3.1 and update error text in `must`
  .github/workflows/test.yml
  .gitignore
  .rspec_status
  Gemfile.lock
  examples/usual/example10.rb
  examples/usual/example8.rb
  examples/usual/example9.rb
  lib/servactory/input_arguments/checks/must.rb
  servactory.gemspec
  spec/examples/wrong/example10_spec.rb
Labels: feature

#4 Add support for Ruby 3.0
  .github/workflows/test.yml
  .rubocop.yml
  lib/servactory/context/dsl.rb
  lib/servactory/input_arguments/checks/inclusion.rb
  lib/servactory/input_arguments/checks/must.rb
  lib/servactory/input_arguments/checks/required.rb
  lib/servactory/input_arguments/checks/type.rb
  lib/servactory/input_arguments/input_argument.rb
  lib/servactory/input_arguments/tools/check.rb
  lib/servactory/internal_arguments/internal_argument.rb
  lib/servactory/internal_arguments/tools/prepare.rb
  lib/servactory/output_arguments/output_argument.rb
  lib/servactory/output_arguments/tools/prepare.rb
  lib/servactory/stage/dsl.rb
  servactory.gemspec
  spec/examples/usual/example10_spec.rb
  spec/examples/usual/example1_spec.rb
  spec/examples/usual/example2_spec.rb
  spec/examples/usual/example3_spec.rb
  spec/examples/usual/example4_spec.rb
  spec/examples/usual/example5_spec.rb
  spec/examples/usual/example6_spec.rb
  spec/examples/usual/example7_spec.rb
  spec/examples/usual/example8_spec.rb
  spec/examples/usual/example9_spec.rb
  spec/examples/wrong/example10_spec.rb
  spec/examples/wrong/example1_spec.rb
  spec/examples/wrong/example2_spec.rb
  spec/examples/wrong/example3_spec.rb
  spec/examples/wrong/example4_spec.rb
  spec/examples/wrong/example5_spec.rb
  spec/examples/wrong/example6_spec.rb
  spec/examples/wrong/example7_spec.rb
  spec/examples/wrong/example8_spec.rb
  spec/examples/wrong/example9_spec.rb
  spec/support/input_argument_helper.rb
  spec/support/shared_examples/input_required_check.rb
  spec/support/shared_examples/input_type_check.rb
Labels: feature

#5 Add support for Ruby 2.7
  .github/workflows/test.yml
  lib/servactory/input_arguments/tools/prepare.rb
  lib/servactory/internal_arguments/tools/prepare.rb
  lib/servactory/output_arguments/tools/prepare.rb
  servactory.gemspec
Labels: feature

#6 Add advanced mode support for `array`
  .rubocop.yml
  examples/usual/example11.rb
  examples/usual/example12.rb
  examples/usual/example13.rb
  lib/servactory/input_arguments/checks/must.rb
  lib/servactory/input_arguments/checks/type.rb
  lib/servactory/input_arguments/input_argument.rb
  sig/input_argument_helper.rbs
  sig/lib/servactory/input_arguments/checks/must.rbs
  sig/lib/servactory/input_arguments/input_argument.rbs
  sig/lib/servactory/utils.rbs
  sig/servactory/utils.rbs
  spec/examples/usual/example11_spec.rb
  spec/examples/usual/example12_spec.rb
  spec/examples/usual/example13_spec.rb
  spec/support/input_argument_helper.rb
  spec/support/shared_examples/input_type_check.rb
Labels: feature

#7 Change the workflow for a release
  .github/release-drafter.yml
  .github/release.yml
  .github/workflows/release-notes.yml
Labels: CI

#8 Add examples to the README
  README.md
Labels: documentation

#10 Add information to the README
  README.md
Labels: documentation

#11 Specify gem versions
  Gemfile.lock
  servactory.gemspec
Labels: dependencies

#12 Improve `required` and `types` checks
  .rubocop.yml
  examples/usual/example17.rb
  lib/servactory/input_arguments/checks/required.rb
  lib/servactory/input_arguments/input_argument.rb
  lib/servactory/input_arguments/option.rb
  sig/input_argument_helper.rbs
  sig/lib/servactory/input_arguments/checks/required.rbs
  sig/lib/servactory/input_arguments/input_argument.rbs
  sig/lib/servactory/input_arguments/option.rbs
  spec/examples/usual/example17_spec.rb
  spec/support/input_argument_helper.rb
  spec/support/shared_examples/input_required_check.rb
Labels: feature

#13 Add checks for the class of the returned result
  spec/examples/usual/example10_spec.rb
  spec/examples/usual/example11_spec.rb
  spec/examples/usual/example12_spec.rb
  spec/examples/usual/example13_spec.rb
  spec/examples/usual/example14_spec.rb
  spec/examples/usual/example15_spec.rb
  spec/examples/usual/example16_spec.rb
  spec/examples/usual/example17_spec.rb
  spec/examples/usual/example1_spec.rb
  spec/examples/usual/example2_spec.rb
  spec/examples/usual/example3_spec.rb
  spec/examples/usual/example4_spec.rb
  spec/examples/usual/example5_spec.rb
  spec/examples/usual/example6_spec.rb
  spec/examples/usual/example7_spec.rb
  spec/examples/usual/example8_spec.rb
  spec/examples/usual/example9_spec.rb
  spec/support/shared_examples/result_class.rb
Labels: tests

#14 Improve work with attributes
  README.md
  examples/usual/example18.rb
  examples/usual/example19.rb
  lib/servactory/context/dsl.rb
  lib/servactory/input_arguments/tools/prepare.rb
  lib/servactory/inputs.rb
  spec/examples/usual/example18_spec.rb
  spec/examples/usual/example19_spec.rb
Labels: feature

#15 Add methods for failures, improve error handling, improve configuration
  .github/workflows/test.yml
  README.md
  examples/usual/example10.rb
  examples/usual/example20.rb
  lib/servactory.rb
  lib/servactory/base.rb
  lib/servactory/configuration.rb
  lib/servactory/configuration/dsl.rb
  lib/servactory/configuration/factory.rb
  lib/servactory/configuration/setup.rb
  lib/servactory/context/callable.rb
  lib/servactory/context/dsl.rb
  lib/servactory/context/store.rb
  lib/servactory/context/workspace.rb
  lib/servactory/context/workspace/error.rb
  lib/servactory/context/workspace/errors.rb
  lib/servactory/input_arguments/options_collection.rb
  lib/servactory/input_arguments/tools/prepare.rb
  lib/servactory/internal_arguments/tools/prepare.rb
  lib/servactory/output_arguments/tools/prepare.rb
  sig/lib/servactory.rbs
  sig/lib/servactory/configuration.rbs
  sig/lib/servactory/configuration/dsl.rbs
  sig/lib/servactory/configuration/factory.rbs
  sig/lib/servactory/configuration/setup.rbs
  sig/lib/servactory/context/callable.rbs
  sig/lib/servactory/context/dsl.rbs
  sig/lib/servactory/context/store.rbs
  sig/lib/servactory/context/workspace.rbs
  sig/lib/servactory/context/workspace/error.rbs
  sig/lib/servactory/context/workspace/errors.rbs
  sig/lib/servactory/input_arguments/dsl.rbs
  sig/lib/servactory/input_arguments/tools/prepare.rbs
  sig/lib/servactory/internal_arguments/tools/prepare.rbs
  sig/lib/servactory/output_arguments/tools/prepare.rbs
  spec/examples/usual/example20_spec.rb
  spec/examples/usual/example9_spec.rb
Labels: feature

#19 Add `as` option to override internal input name
  README.md
  examples/usual/example21.rb
  examples/wrong/example11.rb
  lib/servactory/input_arguments/input_argument.rb
  lib/servactory/input_arguments/tools/prepare.rb
  sig/lib/servactory/input_arguments/input_argument.rbs
  sig/lib/servactory/input_arguments/tools/check.rbs
  spec/examples/usual/example21_spec.rb
  spec/examples/wrong/example11_spec.rb
Labels: feature

#17 Use `Set` instead of `Array`
  lib/servactory/context/workspace.rb
  lib/servactory/context/workspace/errors.rb
  lib/servactory/input_arguments/checks/base.rb
  lib/servactory/input_arguments/checks/errors.rb
  lib/servactory/input_arguments/collection.rb
  lib/servactory/input_arguments/options_collection.rb
  lib/servactory/input_arguments/tools/check.rb
  lib/servactory/input_arguments/tools/check_errors.rb
  lib/servactory/internal_arguments/collection.rb
  lib/servactory/output_arguments/collection.rb
  lib/servactory/stage/methods.rb
  sig/lib/servactory/context/workspace/errors.rbs
  sig/lib/servactory/input_arguments/checks/base.rbs
  sig/lib/servactory/input_arguments/checks/errors.rbs
  sig/lib/servactory/input_arguments/collection.rbs
  sig/lib/servactory/input_arguments/options_collection.rbs
  sig/lib/servactory/input_arguments/tools/check.rbs
  sig/lib/servactory/input_arguments/tools/check_errors.rbs
  sig/lib/servactory/internal_arguments/collection.rbs
  sig/lib/servactory/output_arguments/collection.rbs
  sig/lib/servactory/stage/methods.rbs
Labels: feature

#20 Update versions of dependencies from 15.05.2023
  .rubocop.yml
  Gemfile.lock
Labels: dependencies

#18 Add `call` method and statuses to the result
  README.md
  lib/servactory/context/callable.rb
  lib/servactory/context/workspace/errors.rb
  lib/servactory/result.rb
  sig/lib/servactory/context/callable.rbs
  sig/lib/servactory/result.rbs
  spec/examples/usual/example10_spec.rb
  spec/examples/usual/example11_spec.rb
  spec/examples/usual/example12_spec.rb
  spec/examples/usual/example13_spec.rb
  spec/examples/usual/example14_spec.rb
  spec/examples/usual/example15_spec.rb
  spec/examples/usual/example16_spec.rb
  spec/examples/usual/example17_spec.rb
  spec/examples/usual/example18_spec.rb
  spec/examples/usual/example19_spec.rb
  spec/examples/usual/example1_spec.rb
  spec/examples/usual/example20_spec.rb
  spec/examples/usual/example21_spec.rb
  spec/examples/usual/example2_spec.rb
  spec/examples/usual/example3_spec.rb
  spec/examples/usual/example4_spec.rb
  spec/examples/usual/example5_spec.rb
  spec/examples/usual/example6_spec.rb
  spec/examples/usual/example7_spec.rb
  spec/examples/usual/example8_spec.rb
  spec/examples/usual/example9_spec.rb
  spec/examples/wrong/example10_spec.rb
  spec/examples/wrong/example11_spec.rb
  spec/examples/wrong/example1_spec.rb
  spec/examples/wrong/example2_spec.rb
  spec/examples/wrong/example3_spec.rb
  spec/examples/wrong/example4_spec.rb
  spec/examples/wrong/example5_spec.rb
  spec/examples/wrong/example6_spec.rb
  spec/examples/wrong/example7_spec.rb
  spec/examples/wrong/example8_spec.rb
  spec/examples/wrong/example9_spec.rb
  spec/support/shared_examples/failure_result_class.rb
  spec/support/shared_examples/result_class.rb
  spec/support/shared_examples/success_result_class.rb
Labels: feature

#21 Uniform style for adding an element to `Set`
  lib/servactory/input_arguments/checks/base.rb
  lib/servactory/input_arguments/checks/errors.rb
Labels: polish

#22 Improve syntax for `define_input_methods`
  lib/servactory/input_arguments/define_input_method.rb
  lib/servactory/input_arguments/input_argument.rb
  lib/servactory/input_arguments/option.rb
  sig/lib/servactory/input_arguments/define_input_method.rbs
  sig/lib/servactory/input_arguments/option.rbs
Labels: polish

#23 Improve syntax for `define_input_conflicts`
  lib/servactory/input_arguments/define_input_conflict.rb
  lib/servactory/input_arguments/input_argument.rb
  lib/servactory/input_arguments/option.rb
  lib/servactory/input_arguments/options_collection.rb
  sig/lib/servactory/input_arguments/define_input_conflict.rbs
  sig/lib/servactory/input_arguments/option.rbs
  sig/lib/servactory/input_arguments/options_collection.rbs
Labels: polish

#25 Add Rails support for use as needed
  lib/servactory.rb
  lib/servactory/engine.rb
Labels: feature

#27 Use `Make` instead of `Stage`
  README.md
  examples/usual/example1.rb
  examples/usual/example10.rb
  examples/usual/example11.rb
  examples/usual/example12.rb
  examples/usual/example13.rb
  examples/usual/example14.rb
  examples/usual/example15.rb
  examples/usual/example16.rb
  examples/usual/example17.rb
  examples/usual/example18.rb
  examples/usual/example19.rb
  examples/usual/example2.rb
  examples/usual/example20.rb
  examples/usual/example21.rb
  examples/usual/example3.rb
  examples/usual/example4.rb
  examples/usual/example5.rb
  examples/usual/example6.rb
  examples/usual/example7.rb
  examples/usual/example8.rb
  examples/usual/example9.rb
  examples/wrong/example1.rb
  examples/wrong/example10.rb
  examples/wrong/example11.rb
  examples/wrong/example12.rb
  examples/wrong/example2.rb
  examples/wrong/example3.rb
  examples/wrong/example4.rb
  examples/wrong/example5.rb
  examples/wrong/example9.rb
  lib/servactory/base.rb
  lib/servactory/context/callable.rb
  lib/servactory/make_methods/collection.rb
  lib/servactory/make_methods/dsl.rb
  lib/servactory/make_methods/make_method.rb
  lib/servactory/make_methods/workbench.rb
  lib/servactory/stage/dsl.rb
  lib/servactory/stage/factory.rb
  lib/servactory/stage/handyman.rb
  sig/lib/servactory/base.rbs
  sig/lib/servactory/make_methods/collection.rbs
  sig/lib/servactory/make_methods/dsl.rbs
  sig/lib/servactory/make_methods/make_method.rbs
  sig/lib/servactory/make_methods/workbench.rbs
  sig/lib/servactory/stage/dsl.rbs
  sig/lib/servactory/stage/factory.rbs
  sig/lib/servactory/stage/handyman.rbs
  sig/lib/servactory/stage/method.rbs
Labels: breaking-change

#26 Improve inheritance for attributes and methods
  README.md
  examples/usual/example22.rb
  lib/servactory/input_arguments/collection.rb
  lib/servactory/input_arguments/dsl.rb
  lib/servactory/internal_arguments/collection.rb
  lib/servactory/internal_arguments/dsl.rb
  lib/servactory/internal_arguments/workbench.rb
  lib/servactory/make_methods/collection.rb
  lib/servactory/make_methods/dsl.rb
  lib/servactory/make_methods/workbench.rb
  lib/servactory/output_arguments/collection.rb
  lib/servactory/output_arguments/dsl.rb
  spec/examples/usual/example22_spec.rb
Labels: feature

#28 Update versions of dependencies from 20.05.2023
  .rubocop.yml
  Gemfile.lock
  spec/examples/usual/example22_spec.rb
  spec/spec_helper.rb
Labels: dependencies

#29 Fix work with input attribute options
  .github/release.yml
  .rubocop.yml
  examples/usual/example23.rb
  lib/servactory/context/callable.rb
  lib/servactory/input_arguments/dsl.rb
  lib/servactory/input_arguments/input_argument.rb
  lib/servactory/input_arguments/tools/check.rb
  lib/servactory/input_arguments/workbench.rb
  sig/lib/servactory/input_arguments/dsl.rbs
  sig/lib/servactory/input_arguments/input_argument.rbs
  sig/lib/servactory/input_arguments/tools/check.rbs
  sig/lib/servactory/input_arguments/workbench.rbs
  spec/examples/usual/example23_spec.rb
Labels: fix

#30 Add custom message support for `inclusion` option
  examples/usual/example24.rb
  lib/servactory/input_arguments/checks/inclusion.rb
  lib/servactory/input_arguments/input_argument.rb
  spec/examples/usual/example24_spec.rb
Labels: feature

#32 Add Yard
  .yardopts
  Gemfile.lock
  lib/servactory/utils.rb
  servactory.gemspec
Labels: documentation

#37 Add documentation
  docs/.gitignore
  docs/README.md
  docs/babel.config.js
  docs/docs/getting-started.md
  docs/docs/home.md
  docs/docs/i18n.md
  docs/docs/usage/_category_.yml
  docs/docs/usage/call.md
  docs/docs/usage/failures.md
  docs/docs/usage/input.md
  docs/docs/usage/internal.md
  docs/docs/usage/make.md
  docs/docs/usage/minimal_example.md
  docs/docs/usage/output.md
  docs/docs/usage/result.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/pages/markdown-page.md
  docs/static/.nojekyll
  docs/static/img/favicon.ico
  docs/tsconfig.json
  docs/yarn.lock
Labels: documentation

#38 Add method shortcuts
  README.md
  docs/docs/usage/make.md
  examples/application_service/base.rb
  examples/usual/example28.rb
  lib/servactory/configuration/factory.rb
  lib/servactory/configuration/setup.rb
  lib/servactory/context/configuration.rb
  lib/servactory/methods/dsl.rb
  lib/servactory/methods/shortcuts/collection.rb
  lib/servactory/methods/workbench.rb
  sig/lib/servactory/configuration/factory.rbs
  sig/lib/servactory/configuration/setup.rbs
  sig/lib/servactory/context/configuration.rbs
  sig/lib/servactory/methods/dsl.rbs
  sig/lib/servactory/methods/shortcuts/collection.rbs
  spec/examples/usual/example28_spec.rb
Labels: feature

#39 Apply new documentation
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/docs/home.md
  docs/docs/usage/minimal_example.md
  docs/docusaurus.config.js
  docs/package.json
  docs/pages/CHANGELOG.md
  docs/pages/CODE_OF_CONDUCT.md
  docs/pages/CONTRIBUTING.md
  docs/pages/getting-started.md
  docs/pages/home.md
  docs/pages/i18n.md
  docs/pages/testing.md
  docs/pages/usage/_category_.yml
  docs/pages/usage/call.md
  docs/pages/usage/configuration.md
  docs/pages/usage/failures.md
  docs/pages/usage/input.md
  docs/pages/usage/internal.md
  docs/pages/usage/make.md
  docs/pages/usage/output.md
  docs/pages/usage/result.md
  docs/static/robots.txt
  docs/yarn.lock
Labels: documentation

#40 Update versions of dependencies from 27.05.2023
  Gemfile.lock
  docs/yarn.lock
Labels: dependencies

#42 Improve the appearance of documentation
  docs/docusaurus.config.js
  docs/pages/usage/failures.md
  docs/pages/usage/input.md
  docs/pages/usage/internal.md
  docs/pages/usage/make.md
  docs/pages/usage/output.md
  docs/src/css/custom.css
Labels: documentation

#43 Rename "check" to "validation"
  docs/pages/usage/input.md
  lib/servactory/context/callable.rb
  lib/servactory/inputs/input.rb
  lib/servactory/inputs/tools/find_unnecessary.rb
  lib/servactory/inputs/tools/rules.rb
  lib/servactory/inputs/tools/validation.rb
  lib/servactory/inputs/validations/base.rb
  lib/servactory/inputs/validations/errors.rb
  lib/servactory/inputs/validations/inclusion.rb
  lib/servactory/inputs/validations/must.rb
  lib/servactory/inputs/validations/required.rb
  lib/servactory/inputs/validations/type.rb
  lib/servactory/inputs/workbench.rb
  lib/servactory/internals/tools/prepare.rb
  lib/servactory/internals/validations/base.rb
  lib/servactory/internals/validations/type.rb
  lib/servactory/outputs/tools/conflicts.rb
  lib/servactory/outputs/tools/prepare.rb
  lib/servactory/outputs/validations/base.rb
  lib/servactory/outputs/validations/type.rb
  lib/servactory/outputs/workbench.rb
  sig/lib/servactory/inputs/checks/base.rbs
  sig/lib/servactory/inputs/checks/errors.rbs
  sig/lib/servactory/inputs/checks/inclusion.rbs
  sig/lib/servactory/inputs/checks/must.rbs
  sig/lib/servactory/inputs/checks/required.rbs
  sig/lib/servactory/inputs/checks/type.rbs
  sig/lib/servactory/inputs/tools/check.rbs
  sig/lib/servactory/inputs/tools/find_unnecessary.rbs
  sig/lib/servactory/inputs/tools/rules.rbs
  sig/lib/servactory/inputs/workbench.rbs
  sig/lib/servactory/internals/checks/base.rbs
  sig/lib/servactory/internals/checks/type.rbs
  sig/lib/servactory/outputs/checks/base.rbs
  sig/lib/servactory/outputs/checks/type.rbs
  sig/lib/servactory/outputs/tools/conflicts.rbs
  sig/lib/servactory/outputs/tools/prepare.rbs
Labels: polish

#45 Rename "check" to "validation"
  docs/pages/usage/input.md
  lib/servactory/inputs/input.rb
  lib/servactory/inputs/option.rb
  lib/servactory/inputs/options_collection.rb
  lib/servactory/inputs/tools/validation.rb
  sig/lib/servactory/inputs/option.rbs
  sig/lib/servactory/inputs/options_collection.rbs
  sig/lib/servactory/inputs/tools/check.rbs
Labels: polish

#44 Add Russian version of documentation
  docs/docusaurus.config.js
  docs/i18n/ru/docusaurus-plugin-content-docs/current/CHANGELOG.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/CODE_OF_CONDUCT.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/CONTRIBUTING.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/getting-started.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/home.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/i18n.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/testing.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/_category_.yml
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/call.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/configuration.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/failures.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/input.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/internal.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/make.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/output.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/result.md
  docs/pages/usage/failures.md
  docs/pages/usage/make.md
Labels: documentation

#46 Add Russian version of documentation
  docs/pages/CHANGELOG.md
Labels: documentation

#48 Add "Advanced mode" examples
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/input.md
  docs/pages/usage/input.md
Labels: documentation

#49 Add `unless` for `make`
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/make.md
  examples/usual/example29.rb
  examples/usual/example30.rb
  examples/usual/example31.rb
  examples/usual/example32.rb
  lib/servactory/inputs/input.rb
  lib/servactory/methods/method.rb
  lib/servactory/methods/workbench.rb
  lib/servactory/outputs/output.rb
  lib/servactory/utils.rb
  sig/lib/servactory/methods/method.rbs
  sig/lib/servactory/methods/workbench.rbs
  sig/lib/servactory/utils.rbs
  spec/examples/usual/example29_spec.rb
  spec/examples/usual/example30_spec.rb
  spec/examples/usual/example31_spec.rb
  spec/examples/usual/example32_spec.rb
Labels: feature

#50 Add use of `call` method if `make` was not used
  docs/i18n/ru/docusaurus-plugin-content-docs/current/home.md
  docs/pages/home.md
  examples/usual/example33.rb
  examples/wrong/example13.rb
  lib/servactory/context/workspace.rb
  lib/servactory/methods/collection.rb
  lib/servactory/methods/workbench.rb
  sig/lib/servactory/methods/workbench.rbs
  spec/examples/usual/example33_spec.rb
  spec/examples/wrong/example13_spec.rb
Labels: feature

#51 Improve `internal` behavior for `input`
  examples/wrong/example13.rb
  examples/wrong/example14.rb
  examples/wrong/example15.rb
  lib/servactory/inputs/tools/prepare.rb
  spec/examples/wrong/example14_spec.rb
  spec/examples/wrong/example15_spec.rb
Labels: feature

#52 Add search
  docs/docusaurus.config.js
  docs/package.json
  docs/src/css/custom.css
  docs/yarn.lock
Labels: documentation

#47 Fix typos in Russian documentation
  docs/i18n/ru/docusaurus-plugin-content-docs/current/getting-started.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/home.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/call.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/configuration.md
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/failures.md
Labels: documentation

#54 Add `position` option for `make`
  docs/i18n/ru/docusaurus-plugin-content-docs/current/usage/make.md
  docs/pages/usage/make.md
  examples/usual/example35.rb
  lib/servactory/methods/collection.rb
  lib/servactory/methods/dsl.rb
  lib/servactory/methods/method.rb
  lib/servactory/methods/workbench.rb
  sig/lib/servactory/inputs/tools/check_errors.rbs
  sig/lib/servactory/methods/collection.rbs
  sig/lib/servactory/methods/dsl.rbs
  sig/lib/servactory/methods/method.rbs
  spec/examples/usual/example35_spec.rb
Labels: feature
